# Generated by Django 5.2.8 on 2025-11-13 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, help_text='User, die Zugriff auf dieses Board haben.', related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Anzeigename der Spalte, z.B. 'To Do'.", max_length=100)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'Review'), ('DONE', 'Done')], help_text='Logischer Status der Spalte (To Do, In Progress, Review, Done).', max_length=20)),
                ('position', models.PositiveIntegerField(default=0, help_text='Reihenfolge der Spalten im Board.')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='boards_app.board')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kurzer, prägnanter Titel der Task.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Ausführliche Beschreibung der Task.')),
                ('due_date', models.DateField(blank=True, help_text='Fälligkeitsdatum der Task.', null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Priorität der Task.', max_length=10)),
                ('position', models.PositiveIntegerField(default=0, help_text='Reihenfolge innerhalb der Spalte.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Erstellzeitpunkt der Task.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Änderung.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, an dem die Task als Done markiert wurde.', null=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='Wer ist für die Umsetzung zuständig?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(help_text='Zu welchem Board gehört die Task?', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards_app.board')),
                ('column', models.ForeignKey(blank=True, help_text='In welcher Spalte (Status) befindet sich die Task?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='boards_app.column')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Wer soll die Task reviewen?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['column__position', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Wann wurde die Aktivität erstellt?')),
                ('author', models.ForeignKey(blank=True, help_text='Wer hat den Kommentar / die Aktivität erstellt?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Zu welcher Task gehört diese Aktivität?', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='boards_app.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
